USE world_bank_data;

ALTER TABLE countries
ADD COLUMN country_ID INT AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE population
ADD COLUMN population_ID INT AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE economicindicators
ADD COLUMN economic_ID INT AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE socialindicators
ADD COLUMN social_ID INT AUTO_INCREMENT PRIMARY KEY FIRST;